name: datatypes
description: Brings the whole range of data types, known from other languages like C and C# to Dart. Signed/Unsigned - byte/ubyte (8 bit), short/ushort (16bit), sint/uint (32bit), long/ulong (64bit).
version: 1.0.0
homepage: https://github.com/rednibcoding/datatypes.dart
repository: https://github.com/rednibcoding/datatypes.dart

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
